export const ingredients = [
  { id: "tomate", name: "Tomate", price: 1000, availableForPromo: true },
  { id: "cebolla-morada", name: "Cebolla morada", price: 1000, availableForPromo: true },
  { id: "choclo", name: "Choclo", price: 1000, availableForPromo: true },
  { id: "pimenton", name: "Pimentón", price: 1000, availableForPromo: true },
  { id: "aceituna", name: "Aceituna", price: 1000, availableForPromo: true },
];

export const categories = [
  { id: "promos", name: "Promos" },
  { id: "destacados", name: "Destacados" },
  { id: "pizzas", name: "Menú Pizzas" },
  { id: "burgers", name: "Burger & Sandwich" },
  { id: "acompanamientos", name: "Acompañamientos" },
  { id: "bebestibles", name: "Para beber" },
];

export const products = [
  // PROMOS
  {
    id: "promo-2-pizzas",
    category: "promos",
    type: "promo_pizzas",
    name: "2 Pizzas Familiares",
    shortDescription: "Elige salsa y 3 ingredientes por pizza",
    price: 25900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "promo-burger-2x",
    category: "promos",
    type: "selector-burger-2x",
    name: "Promo Burger 2x",
    shortDescription: "Elige 2 burgers: Rukapillán, Lanín o Llaima",
    price: 15900,
    image: "/productos/burger-generica.png",
    available: true,
  },

  // DESTACADOS
  {
    id: "pizza-villarrica-destacado",
    category: "destacados",
    type: "pizza_fixed",
    name: "Pizza Villarrica",
    shortDescription: "Carne mechada, salame y champiñón",
    price: 15900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-rinihue-destacado",
    category: "destacados",
    type: "pizza_fixed",
    name: "Pizza Riñihue",
    shortDescription: "Pollo BBQ, tocino y cebolla morada",
    price: 14900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "cocteles-destacado",
    category: "destacados",
    type: "selector-happy-hour",
    name: "Cócteles",
    shortDescription: "Pisco Sour, Mojitos, Piña Colada, Spritz y más",
    price: 6000,
    image: "/productos/cocteles.png",
    available: true,
  },
  {
    id: "burger-rukapillan-destacado",
    category: "destacados",
    type: "selector-burger",
    name: "Hamburguesa Rukapillan",
    shortDescription: "Tocino, pepinillo, cebolla morada, queso fundido y salsa BBQ",
    price: 8900,
    image: "/productos/burger-generica.png",
    available: true,
  },
  {
    id: "papas-fritas-doble-destacado",
    category: "destacados",
    type: "simple",
    name: "Papas Fritas Dobles",
    shortDescription: "Porción doble para compartir",
    price: 5990,
    image: "/productos/papas-fritas-doble.png",
    available: true,
  },

  // MENÚ PIZZAS
  {
    id: "arma-tu-pizza",
    category: "pizzas",
    type: "selector-custom-pizza",
    name: "Arma tu Pizza",
    shortDescription: "Elige tu combinación de ingredientes",
    price: 9900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-pellaifa",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Pellaifa",
    shortDescription: "Camarón, tocino y cebolla morada",
    price: 19900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-villarrica",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Villarrica",
    shortDescription: "Carne mechada, salame y champiñón",
    price: 15900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-calafquen",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Calafquén",
    shortDescription: "Pepperoni, lomito de cerdo y cebolla morada",
    price: 15900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-llanquihue",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Llanquihue",
    shortDescription: "Jamón, tomate y aceituna",
    price: 14900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-rinihue",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Riñihue",
    shortDescription: "Pollo BBQ, tocino y cebolla morada",
    price: 14900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-colico",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Colico",
    shortDescription: "Salame, champiñón y aceituna",
    price: 14900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-ramco",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Ramco",
    shortDescription: "Pepperoni, salame y queso",
    price: 14900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-puyehue",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Puyehue",
    shortDescription: "Jamón, champiñón y aceituna",
    price: 13900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-neltume",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Neltume",
    shortDescription: "Champiñón, cebolla morada y pimentón",
    price: 13900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-panguipulli",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Panguipulli",
    shortDescription: "Tomate, choclo y aceituna",
    price: 13900,
    image: "/productos/pizza-generica.png",
    available: true,
  },
  {
    id: "pizza-rupanco",
    category: "pizzas",
    type: "pizza_fixed",
    name: "Pizza Rupanco",
    shortDescription: "Tomate, queso y albahaca",
    price: 13900,
    image: "/productos/pizza-generica.png",
    available: true,
  },

  // BURGER & SANDWICH
  {
    id: "burger-selector",
    category: "burgers",
    type: "selector-burger",
    name: "Burger",
    shortDescription: "Elige entre Rukapillán, Lanín o Llaima",
    price: 8500,
    image: "/productos/burger-generica.png",
    available: true,
  },
  {
    id: "sandwich-selector",
    category: "burgers",
    type: "selector-sandwich",
    name: "Sandwich",
    shortDescription: "Elige proteína y estilo: Solo, Luco, Italiano o Chacarero",
    price: 6900,
    image: "/productos/burger-generica.png",
    available: true,
  },

  // ACOMPAÑAMIENTOS
  {
    id: "chorrillana",
    category: "acompanamientos",
    type: "simple",
    name: "Chorrillana para 2",
    shortDescription: "Para compartir",
    price: 15900,
    image: "/productos/chorrillana.png",
    available: true,
  },
  {
    id: "salchipapas",
    category: "acompanamientos",
    type: "simple",
    name: "Salchipapas",
    shortDescription: "Papas fritas con salchicha",
    price: 6900,
    image: "/productos/salchipapas.png",
    available: true,
  },
  {
    id: "papas-fritas-doble",
    category: "acompanamientos",
    type: "simple",
    name: "Papas Fritas Dobles",
    shortDescription: "Porción doble para compartir",
    price: 5990,
    image: "/productos/papas-fritas-doble.png",
    available: true,
  },
  {
    id: "papas-fritas-individual",
    category: "acompanamientos",
    type: "simple",
    name: "Papas Fritas Individual",
    shortDescription: "Porción individual",
    price: 3900,
    image: "/productos/papas-fritas-doble.png",
    available: true,
  },

  // PARA BEBER
  {
    id: "cocteles-selector",
    category: "bebestibles",
    type: "selector-happy-hour",
    name: "Cócteles",
    shortDescription: "Pisco Sour, Mojitos, Piña Colada, Spritz y más",
    price: 6000,
    image: "/productos/cocteles.png",
    available: true,
  },
  {
    id: "bebidas-selector",
    category: "bebestibles",
    type: "selector-drinks",
    name: "Bebidas",
    shortDescription: "Coca-Cola, Sprite o Fanta",
    price: 3900,
    image: "/productos/bebidas.png",
    available: true,
  },
  {
    id: "cervezas-selector",
    category: "bebestibles",
    type: "selector-beer",
    name: "Cervezas",
    shortDescription: "Kunstmann, Austral o Heineken",
    price: 4000,
    image: "/productos/cervezas.png",
    available: false,
  },
];

export const siteConfig = {
  currency: "CLP",
  locale: "es-CL",
  pizzaSizeLabel: "Familiar 38 cm",
  pizzaDoughOptions: ["Masa normal"],
  happyHour: {
    startsAt: "17:00",
    endsAt: "23:00",
    label: "Happy Hour 17:00 a 23:00",
  },
};